{% set name = "gunpowder" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gunpowder-{{ version }}.tar.gz
  sha256: 46dcf7fdcc0c5aa1ece8e3309f1b2dcfab65b9ea2416cd6f4481f7ae728721ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - augment-nd >=0.1.3
    - funlib.geometry
    - h5py
    - networkx
    - numpy
    - protobuf
    - python >=3.7
    - pytorch
    - requests
    - scikit-image
    - scipy
    - tensorflow
    - tqdm
    - zarr

test:
  imports:
    - gunpowder
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/gunpowder
  summary: A library to facilitate machine learning on large, multi-dimensional images..
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/funkey/gunpowder

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
