{% set name = "gunpowder" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gunpowder-{{ version }}.tar.gz
  sha256: 19e35f667451800f774f4ffc5a52fa16e5c730bfa7fc0fd808e1004fed83752e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - augment-nd
    - funlib.geometry
    - h5py
    - networkx
    - numpy
    - protobuf
    - python >=3.7
    - pytorch
    - requests
    - scikit-image
    - scipy
    - tensorflow
    - tqdm
    - zarr

test:
  imports:
    - gunpowder
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/gunpowder
  summary: A library to facilitate machine learning on large, multi-dimensional images..
  license: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/funkey/gunpowder

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
